---
title: "Sports Project"
author: "Callum & Gugo"
date: "4/27/2022"
output: html_document
---

```{r}
library(tidyverse)     # for data cleaning and plotting
library(gardenR)       # for Lisa's garden data
library(lubridate)     # for date manipulation
library(openintro)     # for the abbr2state() function
library(palmerpenguins)# for Palmer penguin data
library(maps)          # for map data
library(ggmap)         # for mapping points on maps
library(gplots)        # for col2hex() function
library(RColorBrewer)  # for color palettes
library(sf)            # for working with spatial data
library(leaflet)       # for highly customizable mapping
library(ggthemes)      # for more themes (including theme_map())
library(plotly)        # for the ggplotly() - basic interactivity
library(gganimate)     # for adding animation layers to ggplots
library(gifski)        # for creating the gif (don't need to load this library every time,but need it installed)
library(transformr)    # for "tweening" (gganimate)
library(shiny)         # for creating interactive apps
library(patchwork)     # for nicely combining ggplot2 graphs  
library(gt)            # for creating nice tables
library(rvest)         # for scraping data
library(robotstxt)     # for checking if you can scrape data
theme_set(theme_minimal())
```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error=TRUE, message=FALSE, warning=FALSE)
```


```{r}
sports <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2022/2022-03-29/sports.csv')

read_clean <- function(year) {
  raw_df <- readxl::read_excel(glue::glue("2022/2022-03-29/EADA_{year}-{as.double(year)+1}/Schools.xlsx"))

  clean_df <- raw_df %>%
    select(
      unitid, institution_name, city_txt:SUM_PARTIC_WOMEN,
      REV_MEN:TOTAL_REV_MENWOMEN, EXP_MEN:TOTAL_EXP_MENWOMEN, Sports
    ) %>%
    janitor::clean_names() %>%
    mutate(year = as.integer(year), .before = 1) %>%
    type_convert()

  clean_df
}
```

```{r}
sports_1 <- sports %>% 
  select(year, sum_partic_men, sum_partic_women, sports) %>% 
  drop_na(sum_partic_men, sum_partic_women, year, sports) %>% 
  filter(sports %in% c("Basketball", "Swimming", "Soccer", "Golf", "Tennis")) %>% 
  mutate(total = cumsum(sum_partic_men + sum_partic_women))
  
sports_graph <-sports_1 %>% 
  ggplot(aes(x = year, y = total, color = sports)) +
  geom_col() +
  labs(title = "Growth of participation in popular college sports", x = "Year", y = "Total Number of Male and Female Participants")

ggplotly(sports_graph)
  
```




